module.exports = {
    "themeName": "bloomberg",
    "columnHeaderBackgroundColor": "rgb(0, 0, 0)",
    "rowHeaderBackgroundColor": "rgb(0, 0, 0)",
    "topLeftBackgroundColor": "rgb(0, 0, 0)",
    "lineColor": "rgb(53, 53, 53)",
    "backgroundColor2": "rgb(48, 48, 48)",
    "color": "rgb(244, 152, 35)",
    "fontFamily": "Quicksand, sans-serif",
    "backgroundColor": "rgb(13, 4, 68)",
    "columnHeaderColor": "rgb(0, 0, 0)",
    "rowHeaderColor": "rgb(0, 0, 0)",
    "topLeftColor": "rgb(0, 0, 0)",
    "backgroundSelectionColor": "rgb(53, 53, 53)",
    "foregroundSelectionColor": "rgb(0, 0, 0)",
    "columnHeaderForegroundSelectionColor": "rgb(0, 0, 0)",
    "columnHeaderBackgroundSelectionColor": "rgb(53, 53, 53)",
    "rowHeaderForegroundSelectionColor": "rgb(0, 0, 0)",
    "fixedColumnBackgroundSelectionColor": "rgb(53, 53, 53)"
};
